# Generated by Django 2.2 on 2019-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Plan name')),
                ('text', models.TextField(max_length=3000, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In the process'), ('done', 'Completed')], default='new', max_length=20, verbose_name='Status')),
                ('deadline', models.DateField(blank=True, default='', null=True, verbose_name='Deadline')),
            ],
        ),
    ]
