# Generated by Django 2.2 on 2019-09-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
    ]
