# Generated by Django 2.2 on 2019-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190907_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateField(blank=True, default='', max_length=10, null=True, verbose_name='Deadline'),
        ),
    ]
